# .streamlit/secrets.toml
# Copia este archivo a .streamlit/secrets.toml y rellena tus valores

SEEDREAM_API_KEY = "https://fal.run/fal-ai/bytedance/seedream/v5/lite/edit"

# Cloudinary (opcional, para guardar imágenes en la nube)
CLOUDINARY_CLOUD_NAME = "dm23fexp7"
CLOUDINARY_API_KEY    = "314517748988439"
CLOUDINARY_API_SECRET = "1Liw_T0NYBNVlhbM0m8_CrsRGPY"
